spring.application.name=core
spring.config.import=file:docker.properties
module.dir=modules

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/dwh}
spring.datasource.username=${DB_USERNAME:dwh}
spring.datasource.password=${DB_PASSWORD:dwh}
spring.flyway.enabled=true
spring.flyway.schemas=core